# Blueprint metadata
blueprint:
  name: Zigbee2MQTT - Tuya 1-Button Scene Switch SH-SC07
  description: Automate your Tuya 1-Button Scene Switch SH-SC07 via Zigbee2MQTT.
# Controller - Tuya SH-SC07 Shortcut button

    Controller automation for executing any kind of action triggered by the provided Tuya SH-SC07 Shortcut button. Allows to optionally loop an action on a button long press.
    Supports deCONZ, ZHA, Zigbee2MQTT.

    Automations created with this blueprint can be connected with one or more [Hooks](https://epmatt.github.io/awesome-ha-blueprints/docs/blueprints/hooks) supported by this controller.
    Hooks allow to easily create controller-based automations for interacting with media players, lights, covers and more.
    See the list of [Hooks available for this controller](https://epmatt.github.io/awesome-ha-blueprints/docs/blueprints/controllers/ikea_e1812#available-hooks) for additional details.

    ## More Info

    â„¹ï¸ Version 2025.02.13
    ðŸ“ [Changelog](https://epmatt.github.io/awesome-ha-blueprints/docs/blueprints/controllers/ikea_e1812/#changelog)
    ðŸ“• Full documentation regarding this blueprint is available [here](https://epmatt.github.io/awesome-ha-blueprints/docs/blueprints/controllers/ikea_e1812).

    ðŸš€ This blueprint is part of the **[Awesome HA Blueprints](https://epmatt.github.io/awesome-ha-blueprints) project**. Please consider **[leaving a star on GitHub](https://github.com/EPMatt/awesome-ha-blueprints)**! ðŸŒŸ

  source_url: https://github.com/EPMatt/awesome-ha-blueprints/blob/main/blueprints/controllers/ikea_e1812/ikea_e1812.yaml
  domain: automation
  homeassistant:
    min_version: 2024.10.0  
  input:
      integration:
      name: (Required) Integration
      description: Integration used for connecting the remote with Home Assistant. Select one of the available values.
      selector:
        select:
          options:
            - deCONZ
            - ZHA
            - Zigbee2MQTT
     controller_device:
      name: (Required) (deCONZ, ZHA, Zigbee2MQTT) Controller Device
      description: The controller device to use for the automation. Choose a value only if the remote is integrated with deCONZ, ZHA, Zigbee2MQTT.
      default: ''
      selector:
        device:
          filter:
            # source: https://www.zigbee2mqtt.io/devices/SH-SC07.html#tuya-sh-sc07
            - integration: mqtt
              manufacturer: Tuya
              model: SH-SC07 shortcut button
            # For backwards compatability with z2m 1.x. model_id is added to end of model rather than a seperate attribute in z2m 2.x
            - integration: mqtt
              manufacturer: Tuya
              model: SH-SC07 shortcut button
            # source: https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Supported-Devices
            - integration: zha
              manufacturer: Tuya of Sweden
              model: SH-SC07 SHORTCUT Button
            - integration: deconz
              manufacturer: Tuya of Sweden
              model: SH-SC07 SHORTCUT Button
          multiple: false
    helper_last_controller_event:
      name: (Required) Helper - Last Controller Event
      description: Input Text used to store the last event fired by the controller. You will need to manually create a text input entity for this, please read the blueprint Additional Notes for more info.
      default: ''
      selector:
        entity:
          domain: input_text
    # inputs for custom actions
    button_one_short_press:
      name: (Optional) Single Press
      description: Action to run on button single press.
      default: []
      selector:
        action: {}
    button_one_double_press:
      name: (Optional) Double Press 
      description: Action to run on button double press
      default: []
      selector:
        action: {}
    button_one_long_press:
      name: (Optional) Long Press
      description: Action to run on button long press
      default: []
      selector:
        action: # inputs for looping custom actions on long button press events until the corresponding release event is received
    helper_debounce_delay:
      name: (Optional) Helper - Debounce delay
      description:
        Delay used for debouncing RAW controller events, by default set to 0. A value of 0 disables the debouncing feature. Increase this value if you notice custom actions or linked Hooks running multiple times when interacting with the device. When the controller needs to be debounced,
        usually a value of 100 is enough to remove all duplicate events.
      default: 0
      selector:
        number:
          min: 0
          max: 1000
          unit_of_measurement: milliseconds
          mode: box
          step: 10
# Automation schema
variables:
  # convert input tags to variables, to be used in templates
  integration: !input integration
  helper_last_controller_event: !input helper_last_controller_event
  helper_debounce_delay: !input helper_debounce_delay
  # integration id used to select items in the action mapping
  integration_id: '{{ integration | lower }}'
  # mapping between actions and integrations
  actions_mapping:
    deconz:
      one_short_press: ['1002']
      one_double_press: ['1001']
      one_long_press: ['1003']
    zha:
      one_short_press: ['on']
      one_double_press: [move_with_on_off_0_83]
      one_long_press: [stop]
    zigbee2mqtt:
      # source: https://www.zigbee2mqtt.io/devices/E1812.html#ikea-e1812
      one_short_press: ['single']
      one_double_press: ['double']
      one_long_press: ['hold'']
  # pre-choose actions for buttons based on configured integration
  # no need to perform this task at automation runtime
  one_short_press: '{{ actions_mapping[integration_id]["one_short_press"] }}'
  one_double_press: '{{ actions_mapping[integration_id]["one_double_press"] }}'
  one_long_press: '{{ actions_mapping[integration_id]["one_long_press"] }}'
  # build data to send within a controller event
  controller_id: !input controller_device
mode: restart
max_exceeded: silent
triggers:
  # triggers for zigbee2mqtt mqtt device action
  - trigger: device
    domain: mqtt
    device_id: !input controller_device
    type: action
    subtype: 'single'
  - trigger: device
    domain: mqtt
    device_id: !input controller_device
    type: action
    subtype: 'double'
  - trigger: device
    domain: mqtt
    device_id: !input controller_device
    type: action
    subtype: 'hold'
  # triggers for other integrations
  - trigger: event
    event_type:
      - deconz_event
      - zha_event
    event_data:
      device_id: !input controller_device
conditions:
  - condition: and
    conditions:
      # check that the button event is not empty
      - >-
        {%- set trigger_action -%}
        {%- if integration_id == "zigbee2mqtt" -%}
        {{ trigger.payload }}
        {%- elif integration_id == "deconz" -%}
        {{ trigger.event.data.event }}
        {%- elif integration_id == "zha" -%}
        {{ trigger.event.data.command }}{{"_" if trigger.event.data.args|length > 0}}{{ trigger.event.data.args|join("_") }}
        {%- endif -%}
        {%- endset -%}
        {{ trigger_action not in ["","None"] }}
actions:
  # debouncing - when automation is triggered multiple times, the last automation run is the one which completes execution, due to mode restart
  # therefore previous runs must wait for the debounce delay before executing any other action
  # if the delay expires and the automation is still running it means it's the last run and execution can continue
  - delay:
      milliseconds: !input helper_debounce_delay
  # extract button event from the trigger
  # provide a single string value to check against
  - variables:
      trigger_action: >-
        {%- if integration_id == "zigbee2mqtt" -%}
        {{ trigger.payload }}
        {%- elif integration_id == "deconz" -%}
        {{ trigger.event.data.event }}
        {%- elif integration_id == "zha" -%}
        {{ trigger.event.data.command }}{{"_" if trigger.event.data.args|length > 0}}{{ trigger.event.data.args|join("_") }}
        {%- endif -%}
      trigger_delta: '{{ (as_timestamp(now()) - ((states(helper_last_controller_event) | from_json).t if helper_last_controller_event is not none and (states(helper_last_controller_event) | regex_match("^\{((\"a\":\".*\"|\"t\":\d+\.\d+)(,)?){2}\}$")) else as_timestamp("1970-01-01 00:00:00"))) * 1000 }}'
  # update helper
  - action: input_text.set_value
    data:
      entity_id: !input helper_last_controller_event
      value: '{{ {"a":trigger_action,"t":as_timestamp(now())} | to_json }}'
  # choose the sequence to run based on the received button event
  - choose:
      - conditions: '{{ trigger_action | string in one_short_press }}'
        sequence:
          # fire the event
          - event: ahb_controller_event
            event_data:
              controller: '{{ controller_id }}'
              action: one_short_press
          - choose:
              - conditions: []
                sequence: !input one_short_press
      - conditions: '{{ trigger_action | string in one_double_press }}'
        sequence:
          # fire the event
          - event: ahb_controller_event
            event_data:
              controller: '{{ controller_id }}'
              action: one_double_press
          - choose:
              - conditions: []
                sequence: !input one_double_press
      - conditions: '{{ trigger_action | string in one_long_press }}'
        sequence:
          # fire the event
          - event: ahb_controller_event
            event_data:
              controller: '{{ controller_id }}'
              action: one_long_press
          # run the custom action
          - choose:
              - conditions: []
                sequence: !input action_one_long_press
